# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: r
        run: |
           [System.UInt32] $r = 5621210575 % [System.UInt32]::MaxValue
           Write-Host $r
        shell: pwsh
        
      - name: duo
        run: |
            $ResourcesNamePrefix = ${{ github.run_number }} % [System.UInt32]::MaxValue
            $ResourcesNamePrefix2 = ${{ github.run_id }} % [System.UInt32]::MaxValue
            Write-Host '--------------------'
            Write-Host $ResourcesNamePrefix
            Write-Host '===================='
            Write-Host $ResourcesNamePrefix2
            

 

